2024-10-27 11:56 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:00 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:02 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:04 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:50 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:54 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 14:59 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:00 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:01 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:02 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:04 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:08 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:16 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:20 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 15:20 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 16:23 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 16:23 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 16:39 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 18:07 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 19:54 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 20:20 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 20:50 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 20:56 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:01 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:03 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:04 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:04 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:05 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 21:30 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 22:05 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 22:19 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 22:20 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 22:30 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-27 22:32 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 09:27 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 13:17 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 13:17 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 13:22 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 13:23 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 14:32 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:32 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:32 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 14:33 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 18:50 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:50 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:50 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:51 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:52 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 170 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 190 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 200 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:53 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 210 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 220 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 230 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 240 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 250 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 260 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:54 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 270 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 280 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 290 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 300 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 310 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 320 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:55 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 330 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 340 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 350 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 360 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 370 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 380 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:56 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 390 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 400 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 410 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 420 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 430 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 440 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:57 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 450 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 460 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 470 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 480 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 490 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 500 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:58 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 510 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 520 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 530 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 540 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 550 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 560 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 18:59 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 570 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 580 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 590 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 600 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 610 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 620 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:00 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 630 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 640 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 650 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 660 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 670 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 680 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:01 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 690 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 700 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 710 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 720 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 730 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 740 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:02 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 750 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 760 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 770 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 780 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 790 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 800 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:03 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 810 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 820 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 830 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 840 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 850 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 860 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:04 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 870 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 880 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 890 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 900 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 910 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 920 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:05 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 930 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 940 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 950 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 960 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 970 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 980 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:06 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 990 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1000 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1010 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1020 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1030 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1040 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:07 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1050 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1060 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1070 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1080 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1090 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1100 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:08 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1110 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1120 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1130 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1140 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1150 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1160 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:09 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1170 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1180 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1190 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1200 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1210 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1220 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:10 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1230 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1240 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1250 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1260 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1270 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1280 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:11 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1290 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1300 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1310 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1320 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1330 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1340 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:12 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1350 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1360 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1370 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1380 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1390 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1400 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:13 WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 1410 seconds.
Loop thread traceback (most recent call last):
  File "A:\Gay-9696\src\main.py", line 94, in <module>
    main()
  File "A:\Gay-9696\src\main.py", line 91, in main
    client.run(token)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 756, in run
    loop.run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jacke\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "A:\Gay-9696\src\main.py", line 54, in on_message
    print(message.content)

2024-10-28 19:14 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 20:44 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 20:47 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 20:50 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-28 20:52 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-29 08:40 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
2024-10-29 14:12 WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
